import { StyleSheet } from "@react-pdf/renderer";

// Define styles for PDF with visual more modern
export const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#fff",
    padding: 30,
    fontFamily: 'Roboto',
  },
  headerSection: {
    marginBottom: 15,
    paddingBottom: 10,
    borderBottom: '1px solid #e0e0e0',
    backgroundColor: "#F9FAFB",
    padding: 12,
    borderRadius: 8,
  },
  title: {
    fontSize: 16,
    marginBottom: 6,
    fontWeight: 700,
    color: "#00b4cc",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 10,
    marginBottom: 3,
    color: "#4A5568",
    textAlign: "center",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 8,
    gap: 12,
  },
  stat: {
    padding: 6,
    borderRadius: 4,
    backgroundColor: "#F0FFF4",
    width: 70,
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#008c9e",
    borderStyle: "solid",
  },
  statLabel: {
    fontSize: 8,
    color: "#4A5568",
    marginBottom: 2,
  },
  statValue: {
    fontSize: 10,
    fontWeight: 700,
    color: "#008c9e",
  },
  section: {
    margin: 0,
    padding: 0,
    flexGrow: 1,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#008c9e",
    borderRadius: 4,
    padding: 4,
    marginBottom: 6,
    color: "white",
    fontWeight: 500,
  },
  memberRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#edf2f7",
    borderBottomStyle: "solid",
    padding: 4,
    marginBottom: 2,
    backgroundColor: "#FAFAFA",
    borderRadius: 3,
    alignItems: "center",
  },
  memberPhoto: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  memberPhotoImage: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#008c9e",
    objectFit: "cover",
  },
  memberPhotoPlaceholder: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#fce138",
    alignItems: "center",
    justifyContent: "center",
  },
  memberPhotoInitial: {
    color: "#333",
    fontSize: 8,
    fontWeight: "bold",
  },
  memberName: {
    flex: 2,
    fontSize: 8,
    fontWeight: 500,
    color: "#2D3748",
  },
  memberStatus: {
    flex: 1,
    fontSize: 8,
    color: "#4A5568",
    alignItems: "center",
  },
  memberContact: {
    flex: 2,
    fontSize: 8,
    color: "#4A5568",
  },
  statusBadge: {
    fontSize: 7,
    padding: "1 3",
    borderRadius: 3,
    textAlign: "center",
    width: "80%",
  },
  statusActive: {
    backgroundColor: "#C6F6D5",
    color: "#22543D",
    borderWidth: 1,
    borderColor: "#10b981",
  },
  statusInactive: {
    backgroundColor: "#FED7D7",
    color: "#822727",
    borderWidth: 1,
    borderColor: "#F56565",
  },
  statusPending: {
    backgroundColor: "#FEEBC8",
    color: "#744210",
    borderWidth: 1,
    borderColor: "#F6AD55",
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 30,
    right: 30,
    borderTop: "1px solid #E2E8F0",
    paddingTop: 8,
    fontSize: 8,
    color: "#718096",
    textAlign: "center",
  },
  chartContainer: {
    marginVertical: 20,
    alignItems: 'center',
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 10,
    color: "#46b644",
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  legendColor: {
    width: 12,
    height: 12,
    marginRight: 8,
    borderRadius: 6,
  },
  legendText: {
    fontSize: 10,
    color: "#4A5568",
  },
  summaryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#edf2f7',
    borderBottomStyle: 'solid',
  },
  summaryLabel: {
    fontSize: 12,
    color: "#4A5568",
  },
  summaryValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: "#2D3748",
  },
  summaryValuePositive: {
    fontSize: 12,
    fontWeight: 'bold',
    color: "#46b644",
  },
  summaryValueNegative: {
    fontSize: 12,
    fontWeight: 'bold',
    color: "#E53E3E",
  },
  report360Section: {
    marginTop: 25,
    marginBottom: 15,
    borderTop: '1px solid #e0e0e0',
    paddingTop: 20,
    backgroundColor: "#F9FAFB",
    padding: 20,
    borderRadius: 8,
  },
  report360SectionTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: "#46b644",
    marginBottom: 15,
  },
});
