// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vamcxqpesqfnobqpbjaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbWN4cXBlc3Fmbm9icXBiamF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTczMzEsImV4cCI6MjA1OTg3MzMzMX0.HOaip_Wafq6saSMOtpwruN-zowRxcAkJ1AmI1i8nJNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);